# Github Action for adding labels to issues based on project

name: ProjectLabeler
on:
  issues:
    types:
      - assigned

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repo-token: "${{ secrets.GITAPP }}"
